resource_group      = "SYSENG-UNIX-DEV-rg"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             # from portal
vnet_name           = "EUS2-SYSENGDEV-vnet"  
vnet_resource_group = "SYSENG-VNET-Dev-rg"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # from portal
subnet_name         = "EUS2-SYSENG-UNIX-DEV-Subnet"   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 # from portal
vm_name             = "al2023-vm"    
vm_size             = "Standard_D2s_v3"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # your desired VM name
admin_username      = "azureuser"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      # or your choice
ssh_public_key      = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDwvPLPaFkMFu8yvXQUTeXw1fVn0L0DFxhUi91GBxemP2nyPlaKLgsfFHbObZSDsA91F11BW9XFmiK4f4SPp+lVUFes1mMUCCMSmOvqYIwRpc8xOR0AtRtL7NOzjwDIPxI466wLUc1xtxklf117+DCL9g8jNkYzGtlOt7nTCnvfE+XDN3iytCAOmbD2+dLA6xRZRYvqJVua8k91f8tUF62AZc4Rpxenc+6E+S1L4rVisMdxNnoTrIRvkerFJ8OFhBiVjKLpIlp/qeowRpRyYHfWYz/LBv0Kceng3SUfbGxUBiDCSNPQQtPHFIljqc5SmKWeBM/HjtsYQHfL2Vajio1Jb+xNoeuy0ELkv/B4jlNXfndvF+yVFvAfT0s3ISrwCG6m3aArv6bwwimnyBkYdYDc4wNymt/ptT/J9o9AqGzCEi7YbTfzePms0OOJYmxO4RidG7v6KVc1IWftlxRk0dtS26kd5T9VVnQrmolP11J2DlEVYqbk2q750yYrmTucbLfiBIo8dWUL0sKU++QYAdyZbtPNkO+/9kAto/oT6e7EP5l2moNeoDmxr9DOD0h4jy1/gvsF870AZDfx6ITK8/Z/BWQuPQA2GZH9pXAJXq/0GIC/2BrzExVbko4lHyLhApthA3cZ03cfBgEyfbblLvril4tq7Vjf+8GsAZKg3kJxJw== azureuser" # from id_rsa.pub
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # same as reference VM
vm_publisher        = "amazon"
vm_offer            = "al2023"
vm_sku              = "default"
vm_version          = "latest"



